### ISSUE TITLE
Uses API v3 which is now deprecated

### ISSUE THREAD

**Issue by erzz** [gotsunami/gitlab-copy#29] opened 2018-05-30 19:24 UTC
Shouldn't it be using V4?

**Comment by matm** [comment] 2018-05-30 19:37
Probably, yes. Pull request is welcome on this one, thanks! /cc @aboutofpluto

**Comment by erzz** [comment] 2018-06-01 06:45
I'm not a go developer - so wouldn't even really know where to start :) I
can point out the https://docs.gitlab.com/ee/api/v3_to_v4.html page - and
can assist with testing for sure. Also note that v3 will be removed shortly
(v11)

**Comment by matm** [comment] 2018-06-01 07:43
Okay, I'll start investigating. Thanks for reporting it @erzz. We might ask your help for a bit of testing :)

**Comment by matm** [comment] 2018-06-03 22:56
@erzz We just published a new `0.7 RC1` version for testing. 

Please [grab a binary](https://github.com/gotsunami/gitlab-copy/releases/tag/v0.7-rc1) and test `gitlab-copy` a bit! Now using GitLab API v4.

Please report any related bug here, thanks!

**Comment by wilmer281** [comment] 2018-06-19 03:03
hi, 
While using same yaml configuration I am now getting message 404 Not found. The same configuration worked before on v3.

GET https://gitlab.com/api/v4/projects/15853109/issues/14068961/notes: 404 {message: 404 Not found}

**Comment by cacciaresi** [comment] 2018-07-04 17:48
Hi, same issue here, it seems that the issue is related with how _issues_ are being referenced in the new version of the GitLab API. 

I've changed locally the source code from issue.ID =>  issue.IID, to reference the [internal Id](https://docs.gitlab.com/ee/api/#id-vs-iid) and its working as expected.

**Comment by cacciaresi** [comment] 2018-07-04 17:56
To be more specific, I've changed the usage of these functions: _ListIssueNotes_, _migrateIssue_ and _CreateIssueNote_.

Note that the documentation now reflects that _IID_ should be used: https://docs.gitlab.com/ce/api/notes.html#list-project-issue-notes

**Comment by aboutofpluto** [comment] 2018-07-04 17:59
HI Claudio,

Thank you for the information and references.
Could you send us a pull request if you have already changed the source code?
We will fix this as soon as possible.

**Comment by charleech** [comment] 2018-08-03 04:56
Hi,

Regarding to the https://docs.gitlab.com/ce/api/#pagination

Parameter | Description
-- | --
page | Page number (default: 1)
per_page | Number of items to list per page (default: 20, max: 100)

I've around 25+ labels, the gitlab-copy is only copying 20 labels.

Could you please help to determine about the paging during copying?

**Comment by wilmer281** [comment] 2018-08-15 07:31
Hi again,

New version looking good until start copying issues. Error is:

source: 222 notes
--
Copying labels ...
Copying issues ...

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x72a405]

goroutine 1 [running]:
main.(*migration).migrateIssue(0xc420011380, 0x1, 0x867a01, 0xc420394960)
        /home/ab/work/go/src/github.com/gotsunami/gitlab-copy/cmd/gitlab-copy/migration.go:138 +0x3c5
main.(*migration).migrate(0xc420011380, 0x1, 0x1)
        /home/ab/work/go/src/github.com/gotsunami/gitlab-copy/cmd/gitlab-copy/migration.go:375 +0xf22
main.main()
        /home/ab/work/go/src/github.com/gotsunami/gitlab-copy/cmd/gitlab-copy/main.go:156 +0x933

Thanks!

**Comment by matm** [comment] 2019-03-01 22:09
API v4 is used and #36 is fixed. Closing.

**Closed by matm** 2019-03-01 22:09 UTC
Labels: enhancement
